# Generated by Django 4.2.28 on 2026-03-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200, verbose_name="型号")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("Keyboard", "键盘"),
                            ("Mouse", "鼠标"),
                            ("Trackpad", "触控板"),
                            ("Audio", "音频"),
                            ("Cable", "线缆"),
                            ("Stylus", "手写笔"),
                            ("Other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="原价"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="优惠价"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="折扣率"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Accessories",
                "verbose_name_plural": "Accessories",
                "db_table": "accessories",
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, unique=True, verbose_name="用户名"),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=256, verbose_name="密码哈希"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "email",
                    models.CharField(blank=True, max_length=200, verbose_name="eMail"),
                ),
                (
                    "role",
                    models.CharField(default="admin", max_length=50, verbose_name="角色"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "管理员",
                "verbose_name_plural": "管理员",
                "db_table": "admins",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, verbose_name="用户ID")),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("apple", "Apple"),
                            ("dell", "Dell"),
                            ("lenovo", "Lenovo"),
                        ],
                        max_length=50,
                        verbose_name="品牌",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=50, verbose_name="设备类型"),
                ),
                ("model_name", models.CharField(max_length=200, verbose_name="型号名称")),
                (
                    "configuration_id",
                    models.IntegerField(blank=True, null=True, verbose_name="配置ID"),
                ),
                (
                    "selected_config",
                    models.JSONField(blank=True, null=True, verbose_name="选中配置"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "购物车",
                "verbose_name_plural": "购物车",
                "db_table": "cart_items",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="订单号"),
                ),
                ("user_id", models.CharField(max_length=100, verbose_name="用户ID")),
                (
                    "user_name",
                    models.CharField(blank=True, max_length=200, verbose_name="用户名"),
                ),
                (
                    "user_email",
                    models.CharField(blank=True, max_length=200, verbose_name="用户eMail"),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("apple", "Apple"),
                            ("dell", "Dell"),
                            ("lenovo", "Lenovo"),
                        ],
                        max_length=50,
                        verbose_name="品牌",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=50, verbose_name="设备类型"),
                ),
                ("model_name", models.CharField(max_length=200, verbose_name="型号名称")),
                (
                    "selected_cpu",
                    models.CharField(blank=True, max_length=200, verbose_name="CPU"),
                ),
                (
                    "selected_memory",
                    models.CharField(blank=True, max_length=100, verbose_name="Memory"),
                ),
                (
                    "selected_hard_disk",
                    models.CharField(blank=True, max_length=100, verbose_name="硬盘"),
                ),
                (
                    "selected_graphic_card",
                    models.CharField(blank=True, max_length=200, verbose_name="GPU"),
                ),
                (
                    "selected_screen",
                    models.CharField(blank=True, max_length=200, verbose_name="屏幕"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Total Price"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="Remark")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(max_length=50, unique=True, verbose_name="设备类型"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "产品类型",
                "verbose_name_plural": "产品类型",
                "db_table": "product_types",
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=200, verbose_name="型号名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=500, verbose_name="图片URL"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.producttype",
                        verbose_name="设备类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model",
                "verbose_name_plural": "Model",
                "db_table": "product_models",
                "unique_together": {("model_name", "device_type")},
            },
        ),
        migrations.CreateModel(
            name="ProductConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "configuration",
                    models.CharField(max_length=200, verbose_name="配置名称"),
                ),
                (
                    "cpu",
                    models.CharField(blank=True, max_length=200, verbose_name="CPU"),
                ),
                (
                    "memory",
                    models.CharField(blank=True, max_length=100, verbose_name="Memory"),
                ),
                (
                    "hard_disk",
                    models.CharField(blank=True, max_length=100, verbose_name="硬盘"),
                ),
                (
                    "graphic_card",
                    models.CharField(blank=True, max_length=200, verbose_name="GPU"),
                ),
                (
                    "screen",
                    models.CharField(blank=True, max_length=200, verbose_name="屏幕"),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="原价"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="优惠价"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="折扣率"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="device.productmodel",
                        verbose_name="型号",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品配置",
                "verbose_name_plural": "产品配置",
                "db_table": "product_configurations",
            },
        ),
    ]
