# Generated by Django 4.2.28 on 2026-03-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productconfiguration",
            name="changing_config_price",
            field=models.TextField(blank=True, verbose_name="配置价格变更"),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="color_option",
            field=models.TextField(blank=True, verbose_name="颜色选项"),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="configuration_parameters",
            field=models.TextField(blank=True, verbose_name="配置参数"),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="product_link",
            field=models.CharField(blank=True, max_length=500, verbose_name="产品链接"),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="weight",
            field=models.CharField(blank=True, max_length=50, verbose_name="Weight"),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="wifi",
            field=models.CharField(blank=True, max_length=100, verbose_name="Wi-Fi"),
        ),
    ]
