# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_productconfiguration_changing_config_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Notebook', '笔记本'), ('Laptop', '高性能本'), ('Desktop', '台式机'), ('Monitor', '显示器'), ('Docking', '扩展坞')], max_length=50, verbose_name='设备类型')),
                ('brand', models.CharField(default='DELL', max_length=50, verbose_name='品牌')),
                ('model', models.CharField(max_length=200, verbose_name='型号名称')),
                ('basic_config', models.TextField(blank=True, verbose_name='基本配置')),
                ('cpu', models.CharField(blank=True, max_length=500, verbose_name='处理器')),
                ('memory', models.CharField(blank=True, max_length=200, verbose_name='Memory')),
                ('hard_disk', models.CharField(blank=True, max_length=200, verbose_name='硬盘')),
                ('graphic_card', models.CharField(blank=True, max_length=500, verbose_name='GPU')),
                ('wifi', models.CharField(blank=True, max_length=500, verbose_name='Wi-Fi')),
                ('configuration_parameters', models.TextField(blank=True, verbose_name='配置参数（接口/端口）')),
                ('weight', models.TextField(blank=True, verbose_name='Weight/尺寸')),
                ('official_link', models.CharField(blank=True, max_length=500, verbose_name='官方链接')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售价')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='原价')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='折扣率')),
                ('changing_config_price', models.TextField(blank=True, verbose_name='配置升级价格')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Dell 产品',
                'verbose_name_plural': 'Dell 产品',
                'db_table': 'dell_products',
                'ordering': ['device_type', 'model'],
            },
        ),
    ]