# Generated by Django 4.2.28 on 2026-03-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0003_dellproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="LenovoProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("Laptop", "笔记本"), ("Desktop", "台式机")],
                        max_length=50,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        default="Lenovo", max_length=50, verbose_name="品牌"
                    ),
                ),
                ("model", models.CharField(max_length=200, verbose_name="型号名称")),
                (
                    "configuration",
                    models.CharField(blank=True, max_length=200, verbose_name="配置名称"),
                ),
                (
                    "cpu",
                    models.CharField(blank=True, max_length=500, verbose_name="处理器"),
                ),
                (
                    "memory",
                    models.CharField(blank=True, max_length=200, verbose_name="内存"),
                ),
                (
                    "hard_disk",
                    models.CharField(blank=True, max_length=200, verbose_name="硬盘"),
                ),
                (
                    "graphic_card",
                    models.CharField(blank=True, max_length=500, verbose_name="显卡"),
                ),
                (
                    "screen",
                    models.CharField(blank=True, max_length=200, verbose_name="屏幕"),
                ),
                (
                    "wifi",
                    models.CharField(blank=True, max_length=500, verbose_name="无线网络"),
                ),
                (
                    "weight",
                    models.CharField(blank=True, max_length=100, verbose_name="重量"),
                ),
                (
                    "accessary",
                    models.CharField(blank=True, max_length=500, verbose_name="配件"),
                ),
                (
                    "configuration_parameters",
                    models.TextField(blank=True, verbose_name="配置参数（接口/端口）"),
                ),
                (
                    "changing_config_price",
                    models.TextField(blank=True, verbose_name="配置升级价格"),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="优惠价"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="原价"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="折扣率"
                    ),
                ),
                (
                    "product_link",
                    models.CharField(blank=True, max_length=500, verbose_name="产品链接"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Lenovo 产品",
                "verbose_name_plural": "Lenovo 产品",
                "db_table": "lenovo_products",
                "ordering": ["device_type", "model"],
            },
        ),
    ]
