# Generated by Django 4.2.28 on 2026-03-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0004_lenovoproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="基础价格"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="selected_upgrades",
            field=models.JSONField(blank=True, null=True, verbose_name="选中升级配置"),
        ),
        migrations.AddField(
            model_name="order",
            name="upgrade_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="升级费用"
            ),
        ),
    ]
