# Generated by Django 4.2.28 on 2026-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0005_order_base_price_order_selected_upgrades_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dellproduct",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, verbose_name="产品图片URL"),
        ),
        migrations.AddField(
            model_name="lenovoproduct",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, verbose_name="产品图片URL"),
        ),
    ]
