# Generated by Django 4.2.28 on 2026-03-05 09:02

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0006_dellproduct_image_url_lenovoproduct_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("apple", "Apple"),
                            ("dell", "Dell"),
                            ("lenovo", "Lenovo"),
                        ],
                        max_length=50,
                        verbose_name="品牌",
                    ),
                ),
                ("product_id", models.IntegerField(verbose_name="产品ID")),
                ("product_type", models.CharField(max_length=50, verbose_name="产品类型")),
                (
                    "image_type",
                    models.CharField(
                        choices=[("main", "主图"), ("gallery", "副图")],
                        default="gallery",
                        max_length=20,
                        verbose_name="图片类型",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=device.models.product_image_path, verbose_name="产品图片"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="图片标题"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "产品图片",
                "verbose_name_plural": "产品图片",
                "db_table": "product_images",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
